
import lab9.Dba;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import lab9.Usuario;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import lab9.Idiomas;
import lab9.Juego;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felip
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_crud_juegos.getModel();
        modelo.addElement("Crear");
        modelo.addElement("Modificar");
        modelo.addElement("Eliminar");
        cb_crud_juegos.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro = new javax.swing.JFrame();
        txt_Registro = new javax.swing.JLabel();
        btn_Register = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        txt_Usuario = new javax.swing.JLabel();
        txt_Contraseña = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JLabel();
        txt_Correo = new javax.swing.JLabel();
        txt_Edad = new javax.swing.JLabel();
        sp_edad = new javax.swing.JSpinner();
        tf_Nombre = new javax.swing.JTextField();
        tf_Correo = new javax.swing.JTextField();
        tf_Usuario = new javax.swing.JTextField();
        tf_Contraseña = new javax.swing.JTextField();
        MainScr = new javax.swing.JFrame();
        TP_Main = new javax.swing.JTabbedPane();
        Juego = new javax.swing.JPanel();
        cb_crud_juegos = new javax.swing.JComboBox<>();
        btn_gen = new javax.swing.JToggleButton();
        btn_exe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_juegos_all = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_2_juegos = new javax.swing.JTable();
        txt_nombre = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JLabel();
        txt_costo = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_namech = new javax.swing.JTextField();
        tf_cat = new javax.swing.JTextField();
        tf_catch = new javax.swing.JTextField();
        tf_cos = new javax.swing.JTextField();
        tf_cosch = new javax.swing.JTextField();
        Idioma = new javax.swing.JPanel();
        txt_nid = new javax.swing.JLabel();
        txt_idj = new javax.swing.JLabel();
        cb_games = new javax.swing.JComboBox<>();
        tf_nombre_crear_idioma = new javax.swing.JTextField();
        btn_creatid = new javax.swing.JToggleButton();
        btn_addtogame = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtable_idiomas = new javax.swing.JTable();
        Correo = new javax.swing.JPanel();
        txt_for = new javax.swing.JLabel();
        txt_case = new javax.swing.JLabel();
        txt_msg = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_body = new javax.swing.JTextArea();
        tf_for = new javax.swing.JTextField();
        tf_case = new javax.swing.JTextField();
        mb_Archivo = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        AbrirArchivo = new javax.swing.JMenuItem();
        Recientes = new javax.swing.JMenu();
        sep1 = new javax.swing.JPopupMenu.Separator();
        Limpiar = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        BG_Login = new javax.swing.JPanel();
        txt_login = new javax.swing.JLabel();
        txt_user = new javax.swing.JLabel();
        tf_User = new javax.swing.JTextField();
        txt_pass = new javax.swing.JLabel();
        pf_pass = new javax.swing.JPasswordField();
        btn_sign = new javax.swing.JToggleButton();
        btn_reg = new javax.swing.JToggleButton();

        Registro.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Registro.setResizable(false);

        txt_Registro.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_Registro.setText("REGISTRO");

        btn_Register.setText("Registrar");
        btn_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RegisterMouseClicked(evt);
            }
        });
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });

        btn_Back.setText("Regresar");
        btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BackMouseClicked(evt);
            }
        });
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        txt_Usuario.setText("Usuario");

        txt_Contraseña.setText("Contraseña");

        txt_Nombre.setText("Nombre");

        txt_Correo.setText("Correo");

        txt_Edad.setText("Edad");

        javax.swing.GroupLayout RegistroLayout = new javax.swing.GroupLayout(Registro.getContentPane());
        Registro.getContentPane().setLayout(RegistroLayout);
        RegistroLayout.setHorizontalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(RegistroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Usuario)
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(txt_Registro))
                    .addComponent(txt_Nombre)
                    .addComponent(txt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Contraseña)
                    .addComponent(txt_Correo)
                    .addComponent(tf_Correo)
                    .addComponent(tf_Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );
        RegistroLayout.setVerticalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Registro)
                    .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Usuario)
                    .addComponent(txt_Contraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nombre)
                    .addComponent(txt_Correo))
                .addGap(18, 18, 18)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(txt_Edad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        MainScr.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        MainScr.setTitle("Generador de Querys");
        MainScr.setResizable(false);

        TP_Main.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TP_MainStateChanged(evt);
            }
        });

        btn_gen.setText("Generar");

        btn_exe.setText("Ejecutar");
        btn_exe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exeMouseClicked(evt);
            }
        });

        jtable_juegos_all.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoria", "Costo", "Idiomas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtable_juegos_all);
        if (jtable_juegos_all.getColumnModel().getColumnCount() > 0) {
            jtable_juegos_all.getColumnModel().getColumn(0).setResizable(false);
            jtable_juegos_all.getColumnModel().getColumn(1).setResizable(false);
            jtable_juegos_all.getColumnModel().getColumn(2).setResizable(false);
            jtable_juegos_all.getColumnModel().getColumn(3).setResizable(false);
            jtable_juegos_all.getColumnModel().getColumn(4).setResizable(false);
        }

        jtable_2_juegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoria", "Costo", "Idiomas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtable_2_juegos);
        if (jtable_2_juegos.getColumnModel().getColumnCount() > 0) {
            jtable_2_juegos.getColumnModel().getColumn(0).setResizable(false);
            jtable_2_juegos.getColumnModel().getColumn(1).setResizable(false);
            jtable_2_juegos.getColumnModel().getColumn(2).setResizable(false);
            jtable_2_juegos.getColumnModel().getColumn(3).setResizable(false);
        }

        txt_nombre.setText("Nombre");

        txt_categoria.setText("Categoria");

        txt_costo.setText("Costo");

        javax.swing.GroupLayout JuegoLayout = new javax.swing.GroupLayout(Juego);
        Juego.setLayout(JuegoLayout);
        JuegoLayout.setHorizontalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JuegoLayout.createSequentialGroup()
                                .addComponent(cb_crud_juegos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(JuegoLayout.createSequentialGroup()
                                        .addComponent(txt_nombre)
                                        .addGap(20, 20, 20)
                                        .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(JuegoLayout.createSequentialGroup()
                                            .addComponent(txt_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tf_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(JuegoLayout.createSequentialGroup()
                                            .addComponent(txt_categoria)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tf_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(JuegoLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_gen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_exe, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))))
                        .addGap(43, 43, 43)
                        .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_catch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_namech, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_cosch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        JuegoLayout.setVerticalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_exe))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_crud_juegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre)
                            .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_namech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_categoria)
                                .addComponent(tf_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_catch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_gen)
                            .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_costo)
                                .addComponent(tf_cos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_cosch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        TP_Main.addTab("Juego", Juego);

        txt_nid.setText("Nombre de idioma");

        txt_idj.setText("Idioma al juego");

        btn_creatid.setText("Crear");
        btn_creatid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_creatidMouseClicked(evt);
            }
        });

        btn_addtogame.setText("Agregar");
        btn_addtogame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addtogameMouseClicked(evt);
            }
        });

        jtable_idiomas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lenguaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable_idiomas.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtable_idiomas);
        if (jtable_idiomas.getColumnModel().getColumnCount() > 0) {
            jtable_idiomas.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout IdiomaLayout = new javax.swing.GroupLayout(Idioma);
        Idioma.setLayout(IdiomaLayout);
        IdiomaLayout.setHorizontalGroup(
            IdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IdiomaLayout.createSequentialGroup()
                .addGroup(IdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IdiomaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn_creatid, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(btn_addtogame, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IdiomaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(IdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(IdiomaLayout.createSequentialGroup()
                                .addGroup(IdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nid, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombre_crear_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93)
                                .addGroup(IdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_idj, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_games, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        IdiomaLayout.setVerticalGroup(
            IdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IdiomaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(IdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nid)
                    .addComponent(txt_idj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_games, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombre_crear_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(IdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_creatid)
                    .addComponent(btn_addtogame))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        TP_Main.addTab("Idioma", Idioma);

        txt_for.setText("Para");

        txt_case.setText("Asunto");

        txt_msg.setText("Mensaje");

        ta_body.setColumns(20);
        ta_body.setRows(5);
        jScrollPane4.setViewportView(ta_body);

        tf_case.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_caseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CorreoLayout = new javax.swing.GroupLayout(Correo);
        Correo.setLayout(CorreoLayout);
        CorreoLayout.setHorizontalGroup(
            CorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorreoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(CorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_for, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_case, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tf_case, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addComponent(tf_for, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        CorreoLayout.setVerticalGroup(
            CorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorreoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txt_for)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_for, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(txt_case)
                .addGap(18, 18, 18)
                .addComponent(tf_case, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(txt_msg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        TP_Main.addTab("Correo", Correo);

        Archivo.setText("Archivo");

        AbrirArchivo.setText("Abrir Archivo");
        Archivo.add(AbrirArchivo);

        Recientes.setText("Archivos Recientes");
        Archivo.add(Recientes);
        Archivo.add(sep1);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        Archivo.add(Limpiar);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        mb_Archivo.add(Archivo);

        MainScr.setJMenuBar(mb_Archivo);

        javax.swing.GroupLayout MainScrLayout = new javax.swing.GroupLayout(MainScr.getContentPane());
        MainScr.getContentPane().setLayout(MainScrLayout);
        MainScrLayout.setHorizontalGroup(
            MainScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TP_Main)
        );
        MainScrLayout.setVerticalGroup(
            MainScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TP_Main)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        txt_login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_login.setText("LOGIN");

        txt_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_user.setText("Usuario");

        txt_pass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_pass.setText("Contraseña");

        btn_sign.setText("Ingresar");
        btn_sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signMouseClicked(evt);
            }
        });
        btn_sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signActionPerformed(evt);
            }
        });

        btn_reg.setText("Registro");
        btn_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regMouseClicked(evt);
            }
        });
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BG_LoginLayout = new javax.swing.GroupLayout(BG_Login);
        BG_Login.setLayout(BG_LoginLayout);
        BG_LoginLayout.setHorizontalGroup(
            BG_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BG_LoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_login)
                .addGap(265, 265, 265))
            .addGroup(BG_LoginLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(BG_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_pass)
                    .addComponent(txt_user)
                    .addComponent(tf_User)
                    .addComponent(pf_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BG_LoginLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btn_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        BG_LoginLayout.setVerticalGroup(
            BG_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_LoginLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txt_login)
                .addGap(111, 111, 111)
                .addComponent(txt_user)
                .addGap(27, 27, 27)
                .addComponent(tf_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(txt_pass)
                .addGap(28, 28, 28)
                .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(BG_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_signActionPerformed

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regMouseClicked
        // TODO add your handling code here:
        
        Registro.pack();
        Registro.setLocationRelativeTo(this);
        Registro.setAlwaysOnTop(true);
        Registro.setVisible(true);
        
        this.setVisible(false);
        
        
        
        
    }//GEN-LAST:event_btn_regMouseClicked

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseClicked
        // TODO add your handling code here:
       
        
        this.pack();
        this.setLocationRelativeTo(Registro);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
        
        Registro.setVisible(false);
    }//GEN-LAST:event_btn_BackMouseClicked

    private void btn_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegisterMouseClicked
        
        update_usuarios();
        boolean flag=false;
        
        for (Usuario u : usuarios) {
            if(u.getUsername().equals(tf_Usuario.getText())){
                flag=true;
            }
        }
        
        if(tf_Usuario.getText().isEmpty() || tf_Usuario.getText().isEmpty() || tf_Usuario.getText().isEmpty() || tf_Usuario.getText().isEmpty()){
            flag = true;
        }
        if(flag==false){
            
        
        
        String username, nombre, correo, password;
        int edad;
        
        username=tf_Usuario.getText();
        nombre = tf_Nombre.getText();
        correo = tf_Correo.getText();
        password=tf_Contraseña.getText();
        edad = (int) sp_edad.getValue();
        
        Dba db = new Dba("./base1.accdb");
        db.conectar();
        try {
            db.query.execute("Insert into Usuarios (Username,Nombre,Contraseña,edad,Correo) values ('"
                    +username+"','"+nombre+"','"+password+"',"+edad+",'"+correo+"')");
            db.commit();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
        
        JOptionPane.showMessageDialog(Registro, "Se ha registrado correctamente!");
        
        tf_Contraseña.setText("");
        tf_Correo.setText("");
        tf_Nombre.setText("");
        tf_Usuario.setText("");
        sp_edad.setValue(0);
        } else{
            JOptionPane.showMessageDialog(Registro, "Usuario repetido! / Campos vacios");
        }
    }//GEN-LAST:event_btn_RegisterMouseClicked

    private void btn_signMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signMouseClicked
        update_usuarios();
        boolean flag=false;
        for (Usuario u : usuarios) {
            if(u.getUsername().equals(tf_User.getText()) && u.getPassword().equals(pf_pass.getText())){
                flag=true;
            }
        }
        
        if(flag){
            JOptionPane.showMessageDialog(this, "Datos correctos, bienvenido " + tf_User.getText());
            MainScr.pack();
            MainScr.setLocationRelativeTo(this);
            MainScr.setAlwaysOnTop(true);
            MainScr.setVisible(true);
            this.setVisible(false);
            
            update_tabla_crear();
            update_jtable_idiomas();
            
        } else{
            JOptionPane.showMessageDialog(this, "Datos incorrectos");
        }
        
    }//GEN-LAST:event_btn_signMouseClicked

    private void tf_caseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_caseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_caseActionPerformed

    private void btn_exeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exeMouseClicked
        //Crear juego
        if(cb_crud_juegos.getSelectedItem().equals("Crear")){
            String nombre,categoria;
            double costo;
            
            nombre=tf_name.getText();
            categoria = tf_cat.getText();
            costo = Double.parseDouble(tf_cos.getText());
            
            Dba db = new Dba("./base1.accdb");
            db.conectar();
            try {
                db.query.execute("Insert into Juegos (Categoria,Costo,Nombre,Idiomas) values('"+categoria+"','"+costo+"','"
                        +nombre+"','"+""+"')");
                db.commit();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
            
        JOptionPane.showMessageDialog(MainScr, "Juego creado exitosamente!");
        
        update_tabla_crear();
        update_creado_juego();
        
        }
    }//GEN-LAST:event_btn_exeMouseClicked

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LimpiarActionPerformed

    private void btn_creatidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_creatidMouseClicked
        String nombre = tf_nombre_crear_idioma.getText();
        
        Dba db = new Dba("./base1.accdb");
        db.conectar();
        try {
            db.query.execute("Insert into Idiomas (Nombre) values ('"+nombre+"')");
            db.commit();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        db.desconectar();
        
        JOptionPane.showMessageDialog(MainScr, "Idioma creado exitosamente!");
        tf_nombre_crear_idioma.setText("");
        update_jtable_idiomas();
        
    }//GEN-LAST:event_btn_creatidMouseClicked

    private void TP_MainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TP_MainStateChanged
        if(TP_Main.getSelectedIndex()==1){
           cargar_juegos_combobox();
        } else if(TP_Main.getSelectedIndex()==0){
            update_tabla_crear();
        }
    }//GEN-LAST:event_TP_MainStateChanged

    private void btn_addtogameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addtogameMouseClicked
        Juego j = (Juego) cb_games.getSelectedItem();
        
        //traer idiomas que ya tiene el juego seleccionado
        String idiomas="";
        Dba db = new Dba("./base1.accdb");
        db.conectar();
        try {
            db.query.execute("Select (Idiomas) from Juegos where Id="+j.getId());
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {                
                idiomas+=rs.getString(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
        
        DefaultTableModel modelo2 = (DefaultTableModel) jtable_idiomas.getModel();
        int fila = jtable_idiomas.getSelectedRow();
        String n= (String) modelo2.getValueAt(fila, 1);
        String m = idiomas+n+",";
        
        Dba db2 = new Dba("./base1.accdb");
        db2.conectar();
        try {
            db2.query.execute("Update Juegos set Idiomas ='"+m+"' where Id ="+j.getId());
            db2.commit();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db2.desconectar();
        
        JOptionPane.showMessageDialog(MainScr, "Idioma agregado exitosamente!");
        
    }//GEN-LAST:event_btn_addtogameMouseClicked

    public void update_tabla_crear(){
        update_juegos();
        
        //Limpiar tabla
        jtable_juegos_all.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoria", "Costo", "Idiomas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtable_juegos_all);
        if (jtable_juegos_all.getColumnModel().getColumnCount() > 0) {
            jtable_juegos_all.getColumnModel().getColumn(0).setResizable(false);
            jtable_juegos_all.getColumnModel().getColumn(1).setResizable(false);
            jtable_juegos_all.getColumnModel().getColumn(2).setResizable(false);
            jtable_juegos_all.getColumnModel().getColumn(3).setResizable(false);
            jtable_juegos_all.getColumnModel().getColumn(4).setResizable(false);
        }
        
        
        DefaultTableModel modelo = (DefaultTableModel) jtable_juegos_all.getModel();
        for (Juego j : juegos) {
            Object [] newrow = {j.getId(),j.getNombre(),j.getCategoria(),j.getCosto(),j.getIdiomas()};
            modelo.addRow(newrow);
        }
        jtable_juegos_all.setModel(modelo);
    }
    
    public void update_creado_juego(){
        update_juegos();
        
        //Limpiar tabla
        jtable_2_juegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoria", "Costo", "Idiomas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtable_2_juegos);
        if (jtable_2_juegos.getColumnModel().getColumnCount() > 0) {
            jtable_2_juegos.getColumnModel().getColumn(0).setResizable(false);
            jtable_2_juegos.getColumnModel().getColumn(1).setResizable(false);
            jtable_2_juegos.getColumnModel().getColumn(2).setResizable(false);
            jtable_2_juegos.getColumnModel().getColumn(3).setResizable(false);
        }
        
        
        DefaultTableModel modelo = (DefaultTableModel) jtable_2_juegos.getModel();
        for (Juego j : juegos) {
            Object [] newrow = {j.getNombre(),j.getCategoria(),j.getCosto(),j.getIdiomas()};
            modelo.addRow(newrow);
        }
        jtable_2_juegos.setModel(modelo);
    }
    
    public void update_jtable_idiomas(){
        update_idiomas();
        
        //Limpiar tabla
        jtable_idiomas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lenguaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable_idiomas.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtable_idiomas);
        if (jtable_idiomas.getColumnModel().getColumnCount() > 0) {
            jtable_idiomas.getColumnModel().getColumn(0).setResizable(false);
        }
        
        
        DefaultTableModel modelo = (DefaultTableModel) jtable_idiomas.getModel();
        for (Idiomas i : idiomas) {
            Object [] newrow = {i.getId(),i.getNombre()};
            modelo.addRow(newrow);
        }
        jtable_idiomas.setModel(modelo);
    }
    
    public void update_juegos(){
        juegos=new ArrayList();
        Dba db = new Dba("./base1.accdb");
        db.conectar();
        try {
            db.query.execute("Select * from Juegos");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {                
                 juegos.add(new Juego(rs.getInt(1), rs.getString(2), rs.getDouble(3), rs.getString(4), rs.getString(5)));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
    }
    
    public void update_idiomas(){
        idiomas=new ArrayList();
        Dba db = new Dba("./base1.accdb");
        db.conectar();
        try {
            db.query.execute("Select * from Idiomas");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {                
                 idiomas.add(new Idiomas(rs.getInt(1), rs.getString(2)));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
    }
    
    public void update_usuarios(){
        usuarios=new ArrayList();
        Dba db = new Dba("./base1.accdb");
        db.conectar();
        try {
            db.query.execute("Select * from Usuarios");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {                
                 usuarios.add(new Usuario(
                        rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getInt(5), rs.getString(6)));
            }
            /*
            
            while (rs.next()) {                
                usuarios.add(new Usuario(
                        rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getInt(5), rs.getString(6)));
            }
            */
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
    }
    
    public void cargar_juegos_combobox(){
        update_juegos();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_games.getModel();
        for (Juego a : juegos) {
            modelo.addElement(a);
        }
        cb_games.setModel(modelo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirArchivo;
    private javax.swing.JMenu Archivo;
    private javax.swing.JPanel BG_Login;
    private javax.swing.JPanel Correo;
    private javax.swing.JPanel Idioma;
    private javax.swing.JPanel Juego;
    private javax.swing.JMenuItem Limpiar;
    private javax.swing.JFrame MainScr;
    private javax.swing.JMenu Recientes;
    private javax.swing.JFrame Registro;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JTabbedPane TP_Main;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Register;
    private javax.swing.JToggleButton btn_addtogame;
    private javax.swing.JToggleButton btn_creatid;
    private javax.swing.JButton btn_exe;
    private javax.swing.JToggleButton btn_gen;
    private javax.swing.JToggleButton btn_reg;
    private javax.swing.JToggleButton btn_sign;
    private javax.swing.JComboBox<String> cb_crud_juegos;
    private javax.swing.JComboBox<String> cb_games;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtable_2_juegos;
    private javax.swing.JTable jtable_idiomas;
    private javax.swing.JTable jtable_juegos_all;
    private javax.swing.JMenuBar mb_Archivo;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JPopupMenu.Separator sep1;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTextArea ta_body;
    private javax.swing.JTextField tf_Contraseña;
    private javax.swing.JTextField tf_Correo;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JTextField tf_User;
    private javax.swing.JTextField tf_Usuario;
    private javax.swing.JTextField tf_case;
    private javax.swing.JTextField tf_cat;
    private javax.swing.JTextField tf_catch;
    private javax.swing.JTextField tf_cos;
    private javax.swing.JTextField tf_cosch;
    private javax.swing.JTextField tf_for;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_namech;
    private javax.swing.JTextField tf_nombre_crear_idioma;
    private javax.swing.JLabel txt_Contraseña;
    private javax.swing.JLabel txt_Correo;
    private javax.swing.JLabel txt_Edad;
    private javax.swing.JLabel txt_Nombre;
    private javax.swing.JLabel txt_Registro;
    private javax.swing.JLabel txt_Usuario;
    private javax.swing.JLabel txt_case;
    private javax.swing.JLabel txt_categoria;
    private javax.swing.JLabel txt_costo;
    private javax.swing.JLabel txt_for;
    private javax.swing.JLabel txt_idj;
    private javax.swing.JLabel txt_login;
    private javax.swing.JLabel txt_msg;
    private javax.swing.JLabel txt_nid;
    private javax.swing.JLabel txt_nombre;
    private javax.swing.JLabel txt_pass;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Usuario> usuarios = new ArrayList();
    private ArrayList<Juego> juegos = new ArrayList();
    private ArrayList<Idiomas> idiomas = new ArrayList();
    
}
